$(document).ready(function() {
		$('#deleteRoom').hide();
		$('#addRoom').show();
		$('#deleteBuilding').hide();
		$('#addBuilding').hide();
		$('#addroom').click(function(){
			$('#addRoom').show();
			$('#deleteRoom').hide();
			$('#deleteBuilding').hide();
			$('#addBuilding').hide();
			$('#delbtn').hide();
			});
		$('#delroom').click(function(){
			$('#addRoom').hide();
			$('#deleteRoom').show();
			$('#deleteBuilding').hide();
			$('#addBuilding').hide();
			$('#delbtn').hide();
			});
		$('#addbuild').click(function(){
			$('#addRoom').hide();
			$('#deleteRoom').hide();
			$('#deleteBuilding').hide();
			$('#addBuilding').show();
			$('#delbtn').hide();
			});
		$('#delbuild').click(function(){
			$('#addRoom').hide();
			$('#deleteRoom').hide();
			$('#deleteBuilding').show();
			$('#addBuilding').hide();
			$('#delbtn').hide();
			});
		})
